%% ELAS3D-Xtal Post-Processing & Hotspot Analysis
% ------------------------------------------------------------------------------
% This script processes the full-field mechanical response output generated by 
% the ELAS3D-Xtal Fortran solver. It extracts the 3D von Mises stress field, 
% applies Gaussian smoothing to mitigate voxelation artifacts, and identifies 
% critical stress concentration "hotspots" (e.g., near pore boundaries).
%
% Dependency:
%   - Image Processing Toolbox (Required for `imgaussfilt3` and `imregionalmax`)
%
% Inputs:
%   - 'xct_poly_params_SS316L.mat': Workspace file containing grid metadata 
%      generated during the microstructure generation phase.
%   - 'fullfield_poly.h5': HDF5 output file from the Fortran solver containing 
%      the computed stress fields.
%   - 'input_structure_poly.h5': HDF5 file containing the phase and orientation maps.
%
% Outputs:
%   - 2D contour maps of the smoothed von Mises stress field at mid-planes (XY, YZ, XZ).
%   - 3D scatter plot of high-stress regions isolating the top computational hotspots.
%   - 'top_peaks.txt': Text file containing coordinates and magnitudes of maximum stresses.
%
% Core Workflow:
%   1. Load spatial grid parameters and the raw 1D HDF5 stress field.
%   2. Reshape into a 3D grid and apply selective 3D Gaussian smoothing (excluding voids).
%   3. Generate high-resolution 2D cross-sectional stress contour plots.
%   4. Use image processing techniques to identify local maximum stress peaks.
%   5. Render a 3D visualization isolating critical stress concentration regions.
%
% Authors:       Juyoung Jeong and Veera Sundararaghavan
% Affiliation:   Department of Aerospace Engineering, University of Michigan,
%                Ann Arbor, MI 48109, USA.
% Repository:    https://github.com/jjeongGrp/elas3d-xtal
%
% Acknowledgement:
%   This work was supported by the Defense Advanced Research Projects Agency
%   (DARPA) SURGE program under Cooperative Agreement No. HR0011-25-2-0009,
%   'Predictive Real-time Intelligence for Metallic Endurance (PRIME)'.
%
% License:       MIT License (See LICENSE file in the repository)
% ------------------------------------------------------------------------------
format compact; clear; close all;

% =========================================================================
%% 1. Parameter and Field Initialization
% =========================================================================

% --- Load Grid Metadata ---
load('xct_poly_params_SS316L.mat','xvec','yvec','zvec','Nx','Ny','Nz', ...
    'cube_len','N_grains','n_phases');
nx = Nx; ny = Ny; nz = Nz;
L = cube_len;

% Convert physical dimensions from meters/millimeters to microns (um)
xvec = xvec * 1000; 
yvec = yvec * 1000;
zvec = zvec * 1000;
L = L * 1000;

% --- Load von Mises Field from Solver Output ---
vm = h5read('fullfield_poly.h5', '/vm'); % [nx*ny*nz x 1] 1D array
vm3d = reshape(vm, nx, ny, nz);          % Reshape to 3D grid

% --- Load Phase Field (Microstructure) ---
phase = h5read('fullfield_poly.h5', '/pix');
phase3d = reshape(phase, nx, ny, nz);
N_grains = max(phase3d(:));

% --- Load Crystallographic Orientations ---
ori_vec = h5read('input_structure_poly.h5','/orientation');

% =========================================================================
%% 2. Stress Field Smoothening Configuration
% =========================================================================

% Settings for Visuals and Hotspot Detection
vm_limit     = 300;   % Colorbar maximum limit (MPa)
vm_threshold = 250;   % Minimum stress threshold to be considered a "hotspot" (MPa)
N_hotspots   = 3;     % Maximum number of hotspots to track globally
N_peaks = N_hotspots; % Number of top peaks to visually annotate on the 3D plot
sigma_val = 0.4;      % Gaussian smoothing strength (mitigates voxel step-edges)

fprintf('Applying Smoothing (Sigma=%.2f)... ', sigma_val);

% Create logical mask to isolate solid material (ignore internal pore/void space)
mask_solid = phase3d <= N_grains;             
vm_temp = vm3d;
vm_temp(~mask_solid) = 0;

% Apply 3D Gaussian filter to the stress field
numerator   = imgaussfilt3(vm_temp, sigma_val, 'Padding', 0);
denominator = imgaussfilt3(single(mask_solid), sigma_val, 'Padding', 0);
denominator(denominator < 1e-6) = 1;

% Normalize and re-apply void mask
vm3d_smooth = numerator ./ denominator;
vm3d_smooth(~mask_solid) = 0;
fprintf('Done.\n');

% =========================================================================
%% 3. Hotspot Identification
% =========================================================================

% Find strictly local maxima within the 3D smoothed field
local_max_mask = imregionalmax(vm3d_smooth);
% Filter maxima to ensure they are in the solid, and exceed our target threshold
candidate_mask = local_max_mask & mask_solid & (vm3d_smooth/1e6 >= vm_threshold);

[max_i, max_j, max_k] = ind2sub(size(vm3d_smooth), find(candidate_mask));
max_vals = vm3d_smooth(candidate_mask) / 1e6;

% Sort hotspots by descending stress magnitude
[max_vals, sort_idx] = sort(max_vals, 'descend');
max_i = max_i(sort_idx); max_j = max_j(sort_idx); max_k = max_k(sort_idx);

num_hotspots = min(length(max_vals), N_hotspots);
if num_hotspots == 0, error('No hotspots found exceeding the threshold!'); end

% Final working array in MPa
vm_MPa = vm3d_smooth / 1e6;

% =========================================================================
%% 4. Mid-Plane 2D Visualizations
% =========================================================================

% Precompute grid centers
center_x = round(nx / 2);
center_y = round(ny / 2);
center_z = round(nz / 2);

% Extract 2D slices and transpose
vm_yz = squeeze(vm3d_smooth(center_x, :, :))' / 1e6;
vm_xy = squeeze(vm3d_smooth(:, :, center_z))' / 1e6;
vm_xz = squeeze(vm3d_smooth(:, center_y, :))' / 1e6;

% Build plotting meshes
[YY_YZ, ZZ_YZ] = meshgrid(yvec, zvec); 
[XX_XY, YY_XY] = meshgrid(xvec, yvec); 
[XX_XZ, ZZ_XZ] = meshgrid(xvec, zvec); 

% Plot Settings
nlevels = 1500; 
str_lim = 300;
font_sz = 15;
Lm = L/2;
axis_range = [-Lm, Lm];
interval = Lm/2;



% --- Plot 1: Y-Z plane at center X ---
figure; clf;
contourf(YY_YZ, ZZ_YZ, vm_yz, nlevels, 'LineColor','none');
axis xy equal tight; colorbar; colormap turbo;
cb = colorbar;
cb.Label.String = 'von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;
xlabel('Position X_2 (μm)'); ylabel('Position X_3 (μm)');
title('von Mises Stress (MPa), Y-Z at Center X');
set(gca, "FontSize", font_sz)
xlim(axis_range); ylim(axis_range); 
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
clim([0 str_lim])


% --- Plot 2: X-Y plane at center Z ---
figure; clf;
contourf(XX_XY, YY_XY, vm_xy, nlevels, 'LineColor','none');
axis xy equal tight; colorbar; colormap turbo;
cb = colorbar;
cb.Label.String = 'von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;
xlabel('Position X_1 (μm)'); ylabel('Position X_2 (μm)');
title('von Mises Stress (MPa), X-Y at Center Z');
set(gca, "FontSize", font_sz)
xlim(axis_range); ylim(axis_range); 
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
clim([0 str_lim])



% --- Plot 3: X-Z plane at center Y ---
figure; clf;
contourf(XX_XZ, ZZ_XZ, vm_xz, nlevels, 'LineColor','none');
axis xy equal tight; colorbar; colormap turbo;
cb = colorbar;
cb.Label.String = 'von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;
xlabel('Position X_1 (μm)'); ylabel('Position X_3 (μm)');
title('von Mises Stress (MPa), X-Z at Center Y');
set(gca, "FontSize", font_sz)
xlim(axis_range); ylim(axis_range); 
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
clim([0 str_lim])



% =========================================================================
%% 5. 3D Plot: High Stress Points & Peak Annotations
% =========================================================================

% 1. Local Maxima Filtering
local_max_mask = imregionalmax(vm3d_smooth);
high_val_mask  = vm_MPa >= vm_threshold;
final_peak_mask = local_max_mask & high_val_mask;

% 2. Extract Data
[p_i, p_j, p_k] = ind2sub(size(vm3d_smooth), find(final_peak_mask));
p_vals = vm_MPa(final_peak_mask);

% 3. Sort and Isolate Top Peaks
[p_vals_sorted, idx_sort] = sort(p_vals, 'descend');
num_peaks = min(length(p_vals_sorted), N_peaks);

top_i = p_i(idx_sort(1:num_peaks));
top_j = p_j(idx_sort(1:num_peaks));
top_k = p_k(idx_sort(1:num_peaks));
top_vals = p_vals_sorted(1:num_peaks);

top_x = xvec(top_i); top_y = yvec(top_j); top_z = zvec(top_k);

% 4. Isolate background High Stress cloud
idx_cloud = find(high_val_mask);
[c_i, c_j, c_k] = ind2sub(size(vm3d_smooth), idx_cloud);
cloud_x = xvec(c_i); cloud_y = yvec(c_j); cloud_z = zvec(c_k);
cloud_v = vm_MPa(idx_cloud);

% 5. Save top peaks to text file
num_peaks_to_save = min(3, num_peaks); % Save top 3 (or fewer if less found)
filename = 'top_peaks.txt';
fprintf('\nTop %d Local Maxima (Von Mises Stress):\n', num_peaks_to_save);
for k = 1:num_peaks_to_save
    fprintf('Peak #%d: %.3f MPa at (%.2f, %.2f, %.2f)\n', ...
        k, top_vals(k), top_x(k), top_y(k), top_z(k));
end

fid = fopen(filename, 'w');
fprintf(fid, 'Top %d Local Maxima (Von Mises Stress):\n', num_peaks_to_save);
for k = 1:num_peaks_to_save
    fprintf(fid, 'Peak #%d: %.3f MPa at (%.2f, %.2f, %.2f)\n', ...
        k, top_vals(k), top_x(k), top_y(k), top_z(k));
end
fclose(fid);
fprintf('\nTop peaks saved to %s\n', filename);

% --- Plot 4: 3D High Stress Cloud & Annotations ---
figure; clf; hold on;

% A. Cloud of high stress points
scatter3(cloud_x, cloud_y, cloud_z, 15, cloud_v, 'filled', ...
    'MarkerFaceAlpha', 0.4); % Semi-transparent

% B. Highlight Top Peaks
plot3(top_x, top_y, top_z, 'kp', 'MarkerSize', 18, ...
    'MarkerFaceColor', 'magenta', 'LineWidth', 1.5);

% C. Annotate Peaks
for k = 1:num_peaks
    txt = sprintf(' %.3f MPa\n (%.2f, %.2f, %.2f)', ...
        top_vals(k), top_x(k), top_y(k), top_z(k));
    
    text(top_x(k), top_y(k), top_z(k), txt, ...
        'FontSize', 12, 'FontWeight', 'bold', 'Color', 'k', ...
        'BackgroundColor', [1 1 1 0.7], 'EdgeColor', 'k', ...
        'VerticalAlignment', 'bottom');
end

% Formatting
colormap('turbo');
cb = colorbar;
cb.Label.String = 'von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;
cb.Location = "east";
clim([0, str_lim]);

hx = xlabel('X_1 (\mum)'); set(hx, 'Rotation', 21);
hy = ylabel('X_2 (\mum)'); set(hy, 'Rotation', -21);
zlabel('X_3 (\mum)');
title(sprintf('Top %d Peaks (Threshold > %d MPa)', N_peaks, vm_threshold));

axis equal tight; grid on; box on;
view([-42.71 22.97]);
set(gca, 'FontSize', font_sz, 'LineWidth', 1.2);

hAxes = findobj(gcf,"Type","axes");
hAxes.BoxStyle = "full";

xlim(axis_range); ylim(axis_range); zlim(axis_range);
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
zticks(axis_range(1):interval:axis_range(2));
hold off;