%% Eshelby Microstructure Post-Processor for ELAS3D-Xtal
% ------------------------------------------------------------------------------
% This script visualizes the full-field mechanical response of the Eshelby 
% inclusion problem simulated by the ELAS3D-Xtal solver. It extracts the 
% 3D von Mises stress field from the solver's HDF5 output and maps it back 
% onto the original spatial grid.
%
% Dependency:
%   - Base MATLAB (No external toolboxes required)
%
% Inputs:
%   - 'params_Eshelby_ellipsoidal.mat': Workspace file containing grid 
%     resolutions (nx, ny, nz) and spatial vectors generated by the pre-processor.
%   - 'fullfield_poly.h5': HDF5 output file from the ELAS3D-Xtal solver 
%     containing the computed stress/strain fields.
%
% Outputs:
%   - High-resolution 2D contour plots of the von Mises stress field 
%     sliced at the domain mid-planes (Y-Z, X-Y, and X-Z).
%
% Core Workflow:
%   1. Load spatial grid parameters from the pre-processor workspace.
%   2. Extract the flattened 1D von Mises stress array from the HDF5 output.
%   3. Reshape the 1D data back into a 3D spatial matrix.
%   4. Extract 2D mid-plane slices and render continuous contour maps.
%
% Authors:       Juyoung Jeong and Veera Sundararaghavan
% Affiliation:   Department of Aerospace Engineering, University of Michigan,
%                Ann Arbor, MI 48109, USA.
% Repository:    https://github.com/jjeongGrp/elas3d-xtal
%
% Acknowledgement:
%   This work was supported by the Defense Advanced Research Projects Agency
%   (DARPA) SURGE program under Cooperative Agreement No. HR0011-25-2-0009,
%   'Predictive Real-time Intelligence for Metallic Endurance (PRIME)'.
%
% License:       MIT License (See LICENSE file in the repository)
% ------------------------------------------------------------------------------
clear; close all;

% =========================================================================
%% 1. Initialization and Parameter Loading
% =========================================================================
load('params_Eshelby_ellipsoidal.mat', 'nx', 'ny', 'nz', 'L', ...
     'xvec', 'yvec', 'zvec', 'a1', 'a2', 'a3');

% =========================================================================
%% 2. Plotting Configuration
% =========================================================================
nlevels = 150;          % Number of contour levels for smooth gradients
str_lim = 300;          % Maximum von Mises stress limit for colorbar (MPa) 
font_sz = 15;           % Standardized font size
Lm = L;
axis_range = [-Lm, Lm];
interval = Lm/2;

% =========================================================================
%% 3. Load Field Data (von Mises Stress)
% =========================================================================
% Read the flattened stress field array from the solver's HDF5 output
vm = h5read('fullfield_poly.h5', '/vm'); 

% Reshape the 1D array back into the 3D spatial grid
vm3d = reshape(vm, nx, ny, nz);

% =========================================================================
%% 4. Mid-Plane Visualizations
% =========================================================================

% --- FIGURE 1: Y-Z Plane at Center X ---
figure; clf;
center_x = round(nx / 2);
% Extract slice, transpose for correct image orientation, and convert to MPa
vm_yz = squeeze(vm3d(center_x, :, :))' / 1e6; 

[YY_YZ, ZZ_YZ] = meshgrid(yvec, zvec); 
contourf(YY_YZ, ZZ_YZ, vm_yz, nlevels, 'LineColor','none');
axis xy equal tight; colorbar; colormap turbo;

cb = colorbar;
cb.Label.String = 'Von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;	
					
xlabel('Position X_2 (μm)'); 
ylabel('Position X_3 (μm)');
set(gca, "FontSize", font_sz)
xlim(axis_range); ylim(axis_range); 
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
clim([0 str_lim])


% --- FIGURE 2: X-Y Plane at Center Z ---
figure; clf;
center_z = round(nz / 2);
vm_xy = squeeze(vm3d(:, :, center_z))' / 1e6; 

[XX_XY, YY_XY] = meshgrid(xvec, yvec);
contourf(XX_XY, YY_XY, vm_xy, nlevels, 'LineColor','none');
axis xy equal tight; colorbar; colormap turbo;

cb = colorbar;
cb.Label.String = 'Von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;			
			
xlabel('Position X_1 (μm)'); 
ylabel('Position X_2 (μm)');
set(gca, "FontSize", font_sz)
xlim(axis_range); ylim(axis_range); 
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
clim([0 str_lim])


% --- FIGURE 3: X-Z Plane at Center Y ---
figure; clf;
center_y = round(ny / 2);
vm_xz = squeeze(vm3d(:, center_y, :))' / 1e6;

[XX_XZ, ZZ_XZ] = meshgrid(xvec, zvec);
contourf(XX_XZ, ZZ_XZ, vm_xz, nlevels, 'LineColor','none');
axis xy equal tight; colorbar; colormap turbo;

cb = colorbar;
cb.Label.String = 'Von Mises Stress (MPa)';
cb.Label.FontSize = font_sz;	
					
xlabel('Position X_1 (μm)'); 
ylabel('Position X_3 (μm)');
set(gca, "FontSize", font_sz)
xlim(axis_range); ylim(axis_range); 
xticks(axis_range(1):interval:axis_range(2));
yticks(axis_range(1):interval:axis_range(2));
clim([0 str_lim])